name: PHP Composer

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.8.0
      with:
        php-version: '7.4'
        tools: php-cs-fixer, phpunit

    - name: build php file
      run: php build




    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
