name: PHP syntax check 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: email
      run: git config --global user.email "ravishekr7@gmail.com"
    - name: user
      run: git config --global user.name "ravishekr7"
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: composer install
      run: composer install
    - name: composer update
      run: composer update --lock
    - name: lock file creation
      run: git add composer.lock 
    - name: commit lock file
      run: git commit -m "file should be added"